=== stasgora/xml-editor/xml/account-statement.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="accountStatement" type="accountStatement" />

	<xs:complexType name="accountStatement">
		<xs:all>
			<xs:element name="bank" type="company" />
			<xs:element name="client" type="person" />
			<xs:element name="account" type="account" />
			<xs:element name="period" type="statementPeriod" />
			<xs:element name="transactionHistory" type="transactionHistory" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="transactionHistory">
		<xs:sequence>
			<xs:element name="transaction" type="transaction" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="transaction">
		<xs:sequence>
			<xs:element name="ordered" type="xs:date"/>
			<xs:element name="processed" type="xs:date"/>
			<xs:element name="description">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="300"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="amount" type="twoPlaceDecimal"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="statementPeriod">
		<xs:sequence>
			<xs:element name="from" type="xs:date"/>
			<xs:element name="to" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="startBalance" type="twoPlaceDecimal" use="required"/>
	</xs:complexType>

	<xs:complexType name="accountState">
		<xs:sequence>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="balance" type="twoPlaceDecimal"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="account">
		<xs:all>
			<xs:element name="number">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:pattern value="\d{26}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="currency">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{3}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="credit" type="accountCredit" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="type" type="words" use="required"/>
	</xs:complexType>

	<xs:complexType name="accountCredit">
		<xs:sequence>
			<xs:element name="limit" type="positiveTwoPlaceDecimal"/>
			<xs:element name="interest" type="positiveTwoPlaceDecimal"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="twoPlaceDecimal">
		<xs:restriction base="xs:decimal">
			<xs:pattern value="-?\d+\.\d{2}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="positiveTwoPlaceDecimal">
		<xs:restriction base="xs:decimal">
			<xs:pattern value="\d+\.\d{2}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="company">
		<xs:sequence>
			<xs:element name="name" type="companyName" />
			<xs:element name="address" type="address" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="person">
		<xs:sequence>
			<xs:element name="name" type="fullName" />
			<xs:element name="address" type="address" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="fullName">
		<xs:sequence>
			<xs:element name="firstName" maxOccurs="3">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(\p{Lu}\p{Ll}+)" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="lastName">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(\p{Lu}\p{Ll}+)(-\p{Lu}\p{Ll}+)?" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="address">
		<xs:sequence>
			<xs:element name="street" type="words">
			</xs:element>
			<xs:element name="number">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[1-9][0-9]*((/[1-9][0-9]*\p{L}?)|(\p{L}?))?" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="postCode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{2}-[0-9]{3}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="city">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(\p{Lu}\p{Ll}+)( \p{Lu}\p{Ll}+)*" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="words">
		<xs:restriction base="xs:string">
			<xs:pattern value="((\d+)|(\p{Lu}?\p{Ll}+\.?))( ((\d+)|(\p{Lu}?\p{Ll}+\.?)))*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="companyName">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="companyType" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="companyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="S.A." />
			<xs:enumeration value="s. c." />
			<xs:enumeration value="sp. j." />
			<xs:enumeration value="sp. k." />
			<xs:enumeration value="sp. p." />
			<xs:enumeration value="sp. z o.o." />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== stasgora/xml-editor/src/main/resources/xml/account-statement-1.xml
<?xml version="1.0" encoding="UTF-8"?>

<accountStatement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="account-statement.xsd">
	<bank>
		<name type="S.A.">Plus Bank</name>
		<address>
			<street>Stanów Zjednoczonych</street>
			<number>61A</number>
			<postCode>04-028</postCode>
			<city>Warszawa</city>
		</address>
	</bank>
	<client>
		<name>
			<firstName>Adam</firstName>
			<lastName>Nowakowski</lastName>
		</name>
		<address>
			<street>Wiosenna</street>
			<number>1/10</number>
			<postCode>00-023</postCode>
			<city>Warszawa</city>
		</address>
	</client>
	<account type="Konto Plus">
		<number>46142212994692297296215262</number>
		<currency>PLN</currency>
		<credit>
			<limit>6000.00</limit>
			<interest>16.50</interest>
		</credit>
	</account>
	<period startBalance="9120.00">
		<from>2015-05-08</from>
		<to>2015-06-09</to>
	</period>
	<transactionHistory>
		<transaction>
			<ordered>2015-06-08</ordered>
			<processed>2015-06-08</processed>
			<description>Wypłata karta: Visa w bankomacie: PLUS BANK</description>
			<amount>-200.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-06-06</ordered>
			<processed>2015-06-06</processed>
			<description>Grzegorz Weinowski
ul. Św. Marcin 1, 60-100 Poznań
Przelew środków</description>
			<amount>-700.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-06-04</ordered>
			<processed>2015-06-04</processed>
			<description>Spółdzielnia mieszkaniowa
ul. Wawrzyniaka 15, 60-100 Poznań
Oplata za czynsz</description>
			<amount>-370.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-06-02</ordered>
			<processed>2015-06-02</processed>
			<description>Zapłata karta Visa w POS: Restauracja</description>
			<amount>-30.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-05-31</ordered>
			<processed>2015-05-31</processed>
			<description>Adam Nowakowski
ul. Wiosenna 1/10, 00-023 Warszawa
Wpłata na lokatę</description>
			<amount>-1600.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-05-29</ordered>
			<processed>2015-05-29</processed>
			<description>Zaplata kartą Visa w POS: Sklep spożywczy</description>
			<amount>-130.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-05-27</ordered>
			<processed>2015-05-27</processed>
			<description>Wpływ należności</description>
			<amount>630.00</amount>
		</transaction>
		<transaction>
			<ordered>2015-05-25</ordered>
			<processed>2015-05-25</processed>
			<description>Zwrot za towar</description>
			<amount>1206.00</amount>
		</transaction>
	</transactionHistory>
</accountStatement>

=== stasgora/xml-editor/xml/account-statement-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<accountStatement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="account-statement.xsd">
	<bank>
		<name type="S.A.">Bank Millennium</name>
		<address>
			<street>Stanisława Żaryna</street>
			<number>2A</number>
			<postCode>02-593</postCode>
			<city>Warszawa</city>
		</address>
	</bank>
	<client>
		<name>
			<firstName>Jan</firstName>
			<firstName>Krzysztof</firstName>
			<lastName>Wyszkowski</lastName>
		</name>
		<address>
			<street>Legnicka</street>
			<number>21/42B</number>
			<postCode>53-671</postCode>
			<city>Malbork</city>
		</address>
	</client>
	<account type="Konto standard">
		<number>88130000007400468394332217</number>
		<currency>PLN</currency>
		<credit>
			<limit>14000.00</limit>
			<interest>16.00</interest>
		</credit>
	</account>
	<period startBalance="11711.05">
		<from>2018-10-26</from>
		<to>2018-11-25</to>
	</period>
	<transactionHistory>
		<transaction>
			<ordered>2018-11-21</ordered>
			<processed>2018-11-21</processed>
			<description>Wypłata kartą Mastercard w bankomacie</description>
			<amount>-300.00</amount>
		</transaction>
		<transaction>
			<ordered>2018-11-11</ordered>
			<processed>2018-11-11</processed>
			<description>Spółdzielnia mieszkaniowa
Oplata za czynsz, Listopad</description>
			<amount>-730.00</amount>
		</transaction>
	</transactionHistory>
</accountStatement>
